In [1]:
import torch
import tiktoken
from torch.utils.data import Dataset

Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.
Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.


In [2]:
tokenizer = tiktoken.get_encoding('gpt2')
tokenizer.n_tokens = 50257

In [3]:
class ShakespeareDataset(Dataset):
    def __init__(self, X):
        self.X = X
        self.Y = torch.empty(0)
        self.length_prompts = 100
        self.length_answers = 100
    def __len__(self):
        # Return the number of samples in the dataset
        return self.X.shape[0]

    def __getitem__(self, idx):
        # Return the sample at index idx
        prompt = self.X[idx]  # Get the prompt (input)
        answer = self.Y  # Get the answer (output)
        return prompt, answer, self.length_prompts, self.length_answers

In [4]:
data = open('input.txt', 'r').read()

tokens = tokenizer.encode(data)
X = torch.tensor(tokens).to('cpu')
dataset = ShakespeareDataset(X)

In [5]:
class args :
    def __init__(self):
        self.number_bits = 8
        self.data_size = 64000
        self.dataset = "addition"


In [ ]:
from src.utils import prepare_data

dataset = prepare_data(args(), tokenizer)

ModuleNotFoundError: No module named 'method'

In [47]:
from sklearn.model_selection import train_test_split

train_dataset, test_dataset = train_test_split(dataset, test_size=0.2)

In [48]:
train_loader = torch.utils.data.DataLoader(train_dataset, batch_size=1, shuffle=True)
test_loader = torch.utils.data.DataLoader(test_dataset, batch_size=1, shuffle=False)

In [49]:
device = 'cpu'
for batch, (prompts, target_answers, prompt_length, _) in enumerate(train_loader):
        prompts = prompts.to(device)
        target_answers = target_answers.to(device)
        print(prompts)
        print(target_answers)

        input_tensor = torch.cat((prompts, target_answers.view(-1)), 0)
        print(input_tensor)

        break

tensor([781])
tensor([], size=(1, 0))
tensor([781.])


In [31]:
print(prompts)
print(target_answers)

tensor([2933])
tensor([], size=(1, 0))


In [32]:
target_answers = target_answers.view(-1)

In [33]:
print(target_answers)

tensor([])
