In [2]:
path = 'https://raw.githubusercontent.com/karpathy/char-rnn/master/data/tinyshakespeare/input.txt'


!wget https://raw.githubusercontent.com/karpathy/char-rnn/master/data/tinyshakespeare/input.txt

--2025-03-22 22:02:41--  https://raw.githubusercontent.com/karpathy/char-rnn/master/data/tinyshakespeare/input.txt
Résolution de raw.githubusercontent.com (raw.githubusercontent.com)… 2606:50c0:8002::154, 2606:50c0:8003::154, 2606:50c0:8000::154, ...
Connexion à raw.githubusercontent.com (raw.githubusercontent.com)|2606:50c0:8002::154|:443… connecté.
requête HTTP transmise, en attente de la réponse… 200 OK
Taille : 1115394 (1,1M) [text/plain]
Sauvegarde en : « input.txt »

input.txt           100%[===================>]   1,06M  --.-KB/s    ds 0,04s   

2025-03-22 22:02:42 (27,0 MB/s) — « input.txt » sauvegardé [1115394/1115394]



In [79]:
data = open('input.txt', 'r').read()

In [80]:
import tiktoken
import torch

train_proportion = 0.8
enc = tiktoken.get_encoding('gpt2')
tokenizer = enc

# print vocab size
vocab_size = len(tokenizer.encode(data))
print(vocab_size)


338025


In [39]:
# Choose a token ID that is not used in the encoding
MASK_TOKEN_ID = 2 # Ensure this ID is unused in your model

# Add it to the special token dictionary
enc._special_tokens["<MASK>"] = MASK_TOKEN_ID


In [40]:
text = "This is a <MASK> token."
tokens = enc.encode(text, allowed_special={"<MASK>"})  # Ensure the token is used
print("Encoded:", tokens)

tokens = [MASK_TOKEN_ID]
# Decode back
decoded_text = enc.decode(tokens)
print("Decoded:", decoded_text)


Encoded: [1212, 318, 257, 1279, 31180, 42, 29, 11241, 13]
Decoded: #


In [58]:
enc.n_tokens = 50255


tokens = enc.encode(data)
x = torch.tensor(tokens)
# create batch
batch_size = 32
n_batch = len(x) // batch_size
x = x[:n_batch * batch_size]
x = x.view(n_batch, batch_size, -1)
print(x.shape)
data_train = x[:int(train_proportion * n_batch)]
data_test = x[int(train_proportion * n_batch):]

torch.Size([10563, 32, 1])


In [59]:
input_tensor = data_train[0]

In [60]:
print(input_tensor.shape)

torch.Size([32, 1])


In [61]:
print(input_tensor)

tensor([[ 5962],
        [22307],
        [   25],
        [  198],
        [ 8421],
        [  356],
        [ 5120],
        [  597],
        [ 2252],
        [   11],
        [ 3285],
        [  502],
        [ 2740],
        [   13],
        [  198],
        [  198],
        [ 3237],
        [   25],
        [  198],
        [ 5248],
        [  461],
        [   11],
        [ 2740],
        [   13],
        [  198],
        [  198],
        [ 5962],
        [22307],
        [   25],
        [  198],
        [ 1639],
        [  389]])


In [62]:
print(data_test.shape)

torch.Size([2113, 32, 1])


In [74]:
len(data)

1115394

In [64]:
input_tokens = data_test[0]

In [67]:
print(input_tokens)


tensor([[   32],
        [   25],
        [  198],
        [   46],
        [   11],
        [  277],
        [  494],
        [   11],
        [  277],
        [  494],
        [   11],
        [  277],
        [  494],
        [    0],
        [  198],
        [  817],
        [   88],
        [ 7813],
        [  338],
        [  407],
        [23221],
        [   11],
        [  475],
        [  257],
        [ 3292],
        [   13],
        [  198],
        [13102],
        [  948],
        [  284],
        [17903],
        [  561]])


In [69]:
input_tokens = input_tokens.squeeze(1)

In [71]:
print(input_tokens.shape)
print(input_tokens)

torch.Size([32])
tensor([   32,    25,   198,    46,    11,   277,   494,    11,   277,   494,
           11,   277,   494,     0,   198,   817,    88,  7813,   338,   407,
        23221,    11,   475,   257,  3292,    13,   198, 13102,   948,   284,
        17903,   561])


In [72]:
tokenizer.decode(input_tokens.detach().numpy().tolist())

"A:\nO, fie, fie, fie!\nThy sin's not accidental, but a trade.\nMercy to thee would"